### ISSUE TITLE
Desired function:   lookup :: (...) => Distribution p o -> o -> p

### ISSUE THREAD

**Issue by lpsmith** [wyager/Dist#1]
I am considering using this library for fuzzing some sensitive real-world data into some plausible-ish looking test data,   and was hoping to model a discrete hypergeometric or semi-hypergeometric distribution with partial replacement.

(But today I discovered that the sensitive data points are explicitly marked,  so I can simply remove them from the test data.   As for the rest,  there's still some fuzzing that should probably be applied,   but I'm thinking I can get away with something much more simple for the time being.)

In any case,  this library would be substantially more useful if it can support an `O(log n)` lookup function.

**Comment by wyager** [comment]
Just to be clear, you want to be able to query the probability of a given outcome? I think I can add that; I can replace the member set with a member map.

**Comment by lpsmith** [comment]
Right,  `lookup` would return the (non-normalized) weight of the given element.

I haven't looked inside your library yet,  but I don't understand why you'd have to change your data structure,  unless there's some less-than-clear assumptions on your interface.     In particular,  I don't see how [`insert`](https://hackage.haskell.org/package/Dist-0.3.0.0/docs/Numeric-Probability-Distribution.html#v:insert) could support negative weights unless it is already possible to implement `lookup`.   So unless I'm missing something, either `insert` can only be called with nonnegative weights,  or `lookup` can be implemented in `O(log n)` time on your existing data structure.

**Comment by wyager** [comment]
In fact, `insert` cannot be called with negative weights.  I can see how the description might be confusing. But yes, this library only supports positive real-valued probabilities.

**Comment by wyager** [comment]
Added `lookup`.
